services:
  - type: web
    name: virtual-saree-drape
    env: python
    runtime: python-3.11
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000 --server.address 0.0.0.0
